builds:
  - id: igogpt
    binary: igogpt
    main: ./cmd/igogpt
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - id: igogpt
    builds:
      - igogpt
    format: zip
    name_template: 'igogpt_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
